@startuml

class Context {
}

interface Strategy {

}

class ConcreteStrategyA {
}

class ConcreteStrategyB {
}

Context *-> Strategy
Strategy <|-- ConcreteStrategyA
Strategy <|-- ConcreteStrategyB
@enduml