@startuml

class Main {
}

abstract UIControl {
    draw()
}

class TextBox {
    draw()
}

class CheckBox {
    draw()
}

Main .right.> UIControl
UIControl <|-- TextBox
UIControl <|-- CheckBox
@enduml
