@startuml

abstract Task {
    execute()
    doExecute()
}

note left
auditTrail.record()
doExecute()
end note

class TransferMoney {
}

class GenerateReport {
}

Task <|-- TransferMoney
Task <|-- GenerateReport
@enduml